import '@/assets/styles/globals.css';
import { mikhak } from '@/assets/fonts';
import { Toaster } from 'sonner';
import toastConfigsDefault from '@/configs/toast';
import Providers from '@/providers';
import InitializeUser from '@/components/InitializeUser';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={mikhak.className}>
        <Providers>
          {/* <InitializeUser /> */}
          {children}
        </Providers>
        <Toaster {...toastConfigsDefault} />
      </body>
    </html>
  );
}
