import '@/assets/styles/globals.css';
import { mikhak } from '@/assets/fonts';
import { Toaster } from 'sonner';
import toastConfigsDefault from '@/configs/toast';
import Providers from '@/providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html className="" lang="fa-IR" dir="rtl">
      <body className={mikhak.className}>
        <Providers>{children}</Providers>
        <Toaster {...toastConfigsDefault} />
      </body>
    </html>
  );
}
